apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: scale
rules:
- apiGroups: ["apps"]
  resources: ["deployment", "statefulsets"]
  verbs: ["get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scale-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scale
subjects:
- kind: ServiceAccount
  name: scale
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale
spec:
  selector:
    matchLabels:
      app: scale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scale
    spec:
      serviceAccountName: scale
      containers:
      - name: scale
        image: alpine:3.12.0
        ports:
        - containerPort: 8080
          #args:
          #- --source=service
        command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: scale
  labels:
    app: scale
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
  selector:
    app: scale
